name: Github CI

on:
  schedule:
      - cron:  '0 23 28 * *'
  push:
    branches:
      - 'main'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:

        - name: Check Out Repo 
          uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v3

        # - name: Build and push base image
        #   id: docker_build_base
        #   uses: docker/build-push-action@v6
        #   with:
        #     context: ./
        #     file: ./base.dockerfile
        #     push: true
        #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pytorch-notebook:base, ${{ secrets.DOCKER_HUB_USERNAME }}/pytorch-notebook 

        # - name: Build and push devel image
        #   id: docker_build_devel
        #   uses: docker/build-push-action@v6
        #   with:
        #     context: ./
        #     file: ./base-devel.dockerfile
        #     push: true
        #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pytorch-notebook:devel

        - name: Image digest
          run: |
            echo ${{ steps.docker_build_base.outputs.digest }}
            echo ${{ steps.docker_build_devel.outputs.digest }}
